<a href="https://colab.research.google.com/github/tlochan/deep-learning-challenge/blob/main/Alphabet_Soup_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
appDf = application_df.copy()
appDf.drop(['EIN'],axis=1,inplace=True)
appDf.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column
for col in appDf:
  column = appDf[col]
  print(column.name)
  print(len(column.unique()))

NAME
19568
APPLICATION_TYPE
17
AFFILIATION
6
CLASSIFICATION
71
USE_CASE
5
ORGANIZATION
4
STATUS
2
INCOME_AMT
9
SPECIAL_CONSIDERATIONS
2
ASK_AMT
8747
IS_SUCCESSFUL
2

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
appDf['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    appDf['APPLICATION_TYPE'] = appDf['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
appDf['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_value_counts = appDf['CLASSIFICATION'].value_counts()
class_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value_counts[class_value_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classes = appDf['CLASSIFICATION'].unique()
vals_to_keep =['C1000','C2000','C1200','C3000','C2100','C7000','C1700','C4000','C5000','C1270','C2700']
classifications_to_replace = [i for i in classes if i not in vals_to_keep]

# Replace in dataframe
for cls in classifications_to_replace:
    appDf['CLASSIFICATION'] = appDf['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
appDf['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [26]:
names = appDf['NAME'].value_counts()
name_values =names [names > 100]
print(name_values)

NAME
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                               197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                   166
KNIGHTS OF COLUMBUS                                                    158
HABITAT FOR HUMANITY INTERNATIONAL INC                                 154
TENNESSEE ORDER OF THE EASTERN STAR                                    151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                144
PTA UTAH CONGRESS                                                      140
THE UNITED STATES PONY CLUBS INC                                       136
CIVITAN INTERNATIONAL                                                  131
SIGMA BETA DELTA INC                                                   127
HONOR SOCIETY OF PHI KAPPA PHI                                         107
MONTANA 4-H FOUNDATION INC                                             107
WASHINGTON STATE GRANGE                                                106
UNIVERSITY OF WYOMING                                                  105
DEMOLAY INTERNATIONAL                                                  104
SERTOMA INC                                                            103
Name: count, dtype: int64

In [27]:
# Choose a cutoff value and create a list of names to be replaced
all_names = appDf['NAME'].unique()
name_values = ['PARENT BOOSTER USA INC','TOPS CLUB INC','UNITED STATES BOWLING CONGRESS INC','WASHINGTON STATE UNIVERSITY',
'AMATEUR ATHLETIC UNION OF THE UNITED STATES INC',
'PTA TEXAS CONGRESS','SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC','ALPHA PHI SIGMA',
'TOASTMASTERS INTERNATIONAL','MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS','LITTLE LEAGUE BASEBALL INC','INTERNATIONAL ASSOCIATION OF LIONS CLUBS']
names_to_replace = [i for i in all_names if i not in name_values]

# Replace in dataframe
for i in names_to_replace:
    appDf['NAME'] = appDf['NAME'].replace(i,"Other")

# Check to make sure replacement was successful
appDf['NAME'].value_counts()

NAME
Other                                                28539
PARENT BOOSTER USA INC                                1260
TOPS CLUB INC                                          765
UNITED STATES BOWLING CONGRESS INC                     700
WASHINGTON STATE UNIVERSITY                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC        408
PTA TEXAS CONGRESS                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC          331
ALPHA PHI SIGMA                                        313
TOASTMASTERS INTERNATIONAL                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS      287
LITTLE LEAGUE BASEBALL INC                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS               266
Name: count, dtype: int64

In [10]:
print(appDf.dtypes)
print(appDf.columns)

NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object
Index(['NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [28]:
# Convert categorical data to numeric with `pd.get_dummies`
cat_dummies = pd.get_dummies(appDf[['APPLICATION_TYPE','NAME', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION','INCOME_AMT', 'SPECIAL_CONSIDERATIONS']])
mergedDf = pd.concat([appDf,cat_dummies],axis=1)
mergedDf.drop(['APPLICATION_TYPE', 'AFFILIATION','NAME', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION','INCOME_AMT', 'SPECIAL_CONSIDERATIONS'],axis=1,inplace=True)
mergedDf.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [29]:
# Split our preprocessed data into our features and target arrays
X = mergedDf.copy()
X.drop('IS_SUCCESSFUL',axis=1,inplace=True)
y = mergedDf['IS_SUCCESSFUL'].values.reshape(-1,1)

# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 random_state=97)
print(X_train.shape)
print(X_test.shape)

(25724, 63)
(8575, 63)

In [30]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_features = len(X_train_scaled[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=5,activation='relu', input_dim=num_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=7,activation='relu'))

#Third hidden layer
nn.add(tf.keras.layers.Dense(units=7,activation='sigmoid'))

#Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=5,activation='sigmoid'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 320

 dense_1 (Dense)             (None, 7)                 42

 dense_2 (Dense)             (None, 7)                 56

 dense_3 (Dense)             (None, 5)                 40

 dense_4 (Dense)             (None, 1)                 6

=================================================================
Total params: 464 (1.81 KB)
Trainable params: 464 (1.81 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
# Compile the model
nn.compile(loss='binary_crossentropy',
           optimizer='adam',
           metrics=['accuracy'])

In [33]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=125)

Epoch 1/125
804/804 [==============================] - 5s 3ms/step - loss: 0.6335 - accuracy: 0.6608
Epoch 2/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5423 - accuracy: 0.7428
Epoch 3/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5288 - accuracy: 0.7477
Epoch 4/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5208 - accuracy: 0.7518
Epoch 5/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5175 - accuracy: 0.7519
Epoch 6/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5154 - accuracy: 0.7528
Epoch 7/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5140 - accuracy: 0.7526
Epoch 8/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5122 - accuracy: 0.7527
Epoch 9/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5109 - accuracy: 0.7536
Epoch 10/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5102 - accuracy: 0.7533
Epoch 11/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5095 - accuracy: 0.7535
Epoch 12/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5088 - accuracy: 0.7544
Epoch 13/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5081 - accuracy: 0.7536
Epoch 14/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5082 - accuracy: 0.7538
Epoch 15/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5075 - accuracy: 0.7533
Epoch 16/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5074 - accuracy: 0.7534
Epoch 17/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5069 - accuracy: 0.7536
Epoch 18/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5063 - accuracy: 0.7539
Epoch 19/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5063 - accuracy: 0.7546
Epoch 20/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5064 - accuracy: 0.7532
Epoch 21/125
804/804 [==============================] - 5s 5ms/step - loss: 0.5059 - accuracy: 0.7549
Epoch 22/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5056 - accuracy: 0.7540
Epoch 23/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5054 - accuracy: 0.7548
Epoch 24/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5052 - accuracy: 0.7549
Epoch 25/125
804/804 [==============================] - 4s 6ms/step - loss: 0.5049 - accuracy: 0.7535
Epoch 26/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5051 - accuracy: 0.7542
Epoch 27/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5045 - accuracy: 0.7554
Epoch 28/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5042 - accuracy: 0.7548
Epoch 29/125
804/804 [==============================] - 5s 6ms/step - loss: 0.5041 - accuracy: 0.7533
Epoch 30/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5039 - accuracy: 0.7546
Epoch 31/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5040 - accuracy: 0.7553
Epoch 32/125
804/804 [==============================] - 4s 4ms/step - loss: 0.5035 - accuracy: 0.7550
Epoch 33/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5033 - accuracy: 0.7546
Epoch 34/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5036 - accuracy: 0.7546
Epoch 35/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5032 - accuracy: 0.7547
Epoch 36/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5032 - accuracy: 0.7545
Epoch 37/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5029 - accuracy: 0.7549
Epoch 38/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5029 - accuracy: 0.7547
Epoch 39/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5026 - accuracy: 0.7554
Epoch 40/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5023 - accuracy: 0.7548
Epoch 41/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5025 - accuracy: 0.7541
Epoch 42/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5021 - accuracy: 0.7558
Epoch 43/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5025 - accuracy: 0.7538
Epoch 44/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5021 - accuracy: 0.7557
Epoch 45/125
804/804 [==============================] - 5s 6ms/step - loss: 0.5020 - accuracy: 0.7547
Epoch 46/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5017 - accuracy: 0.7547
Epoch 47/125
804/804 [==============================] - 5s 6ms/step - loss: 0.5020 - accuracy: 0.7549
Epoch 48/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5021 - accuracy: 0.7546
Epoch 49/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5021 - accuracy: 0.7552
Epoch 50/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5016 - accuracy: 0.7546
Epoch 51/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5018 - accuracy: 0.7554
Epoch 52/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5018 - accuracy: 0.7539
Epoch 53/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5016 - accuracy: 0.7550
Epoch 54/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5017 - accuracy: 0.7542
Epoch 55/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5017 - accuracy: 0.7550
Epoch 56/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5015 - accuracy: 0.7542
Epoch 57/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5012 - accuracy: 0.7551
Epoch 58/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5015 - accuracy: 0.7546
Epoch 59/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5015 - accuracy: 0.7554
Epoch 60/125
804/804 [==============================] - 5s 6ms/step - loss: 0.5012 - accuracy: 0.7552
Epoch 61/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5012 - accuracy: 0.7557
Epoch 62/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5017 - accuracy: 0.7556
Epoch 63/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5011 - accuracy: 0.7545
Epoch 64/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5009 - accuracy: 0.7546
Epoch 65/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5013 - accuracy: 0.7554
Epoch 66/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5014 - accuracy: 0.7547
Epoch 67/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5009 - accuracy: 0.7544
Epoch 68/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5010 - accuracy: 0.7554
Epoch 69/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5011 - accuracy: 0.7551
Epoch 70/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5011 - accuracy: 0.7558
Epoch 71/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5010 - accuracy: 0.7548
Epoch 72/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5009 - accuracy: 0.7552
Epoch 73/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5009 - accuracy: 0.7562
Epoch 74/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5008 - accuracy: 0.7557
Epoch 75/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5009 - accuracy: 0.7558
Epoch 76/125
804/804 [==============================] - 5s 6ms/step - loss: 0.5008 - accuracy: 0.7553
Epoch 77/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5007 - accuracy: 0.7559
Epoch 78/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5009 - accuracy: 0.7551
Epoch 79/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5003 - accuracy: 0.7565
Epoch 80/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5010 - accuracy: 0.7546
Epoch 81/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5005 - accuracy: 0.7547
Epoch 82/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5010 - accuracy: 0.7549
Epoch 83/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5007 - accuracy: 0.7559
Epoch 84/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5003 - accuracy: 0.7557
Epoch 85/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5007 - accuracy: 0.7554
Epoch 86/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5003 - accuracy: 0.7557
Epoch 87/125
804/804 [==============================] - 4s 4ms/step - loss: 0.5004 - accuracy: 0.7561
Epoch 88/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5004 - accuracy: 0.7554
Epoch 89/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5002 - accuracy: 0.7550
Epoch 90/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5001 - accuracy: 0.7558
Epoch 91/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5001 - accuracy: 0.7557
Epoch 92/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5003 - accuracy: 0.7560
Epoch 93/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4999 - accuracy: 0.7556
Epoch 94/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5001 - accuracy: 0.7554
Epoch 95/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5002 - accuracy: 0.7554
Epoch 96/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5001 - accuracy: 0.7554
Epoch 97/125
804/804 [==============================] - 4s 5ms/step - loss: 0.5000 - accuracy: 0.7552
Epoch 98/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5003 - accuracy: 0.7557
Epoch 99/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5000 - accuracy: 0.7560
Epoch 100/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5000 - accuracy: 0.7561
Epoch 101/125
804/804 [==============================] - 4s 4ms/step - loss: 0.4998 - accuracy: 0.7565
Epoch 102/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4999 - accuracy: 0.7553
Epoch 103/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4998 - accuracy: 0.7561
Epoch 104/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5000 - accuracy: 0.7558
Epoch 105/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4999 - accuracy: 0.7564
Epoch 106/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4999 - accuracy: 0.7552
Epoch 107/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4998 - accuracy: 0.7557
Epoch 108/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4998 - accuracy: 0.7554
Epoch 109/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5000 - accuracy: 0.7560
Epoch 110/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4997 - accuracy: 0.7563
Epoch 111/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4999 - accuracy: 0.7566
Epoch 112/125
804/804 [==============================] - 3s 4ms/step - loss: 0.5002 - accuracy: 0.7565
Epoch 113/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4996 - accuracy: 0.7560
Epoch 114/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4997 - accuracy: 0.7556
Epoch 115/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4996 - accuracy: 0.7563
Epoch 116/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4998 - accuracy: 0.7557
Epoch 117/125
804/804 [==============================] - 6s 7ms/step - loss: 0.5000 - accuracy: 0.7559
Epoch 118/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4997 - accuracy: 0.7557
Epoch 119/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4997 - accuracy: 0.7560
Epoch 120/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4994 - accuracy: 0.7558
Epoch 121/125
804/804 [==============================] - 4s 5ms/step - loss: 0.4995 - accuracy: 0.7552
Epoch 122/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4996 - accuracy: 0.7559
Epoch 123/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4992 - accuracy: 0.7562
Epoch 124/125
804/804 [==============================] - 5s 6ms/step - loss: 0.4994 - accuracy: 0.7562
Epoch 125/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4996 - accuracy: 0.7561

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5122 - accuracy: 0.7437 - 700ms/epoch - 3ms/step
Loss: 0.512197732925415, Accuracy: 0.7436734437942505

In [35]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharityOptimization.h5')