<a href="https://colab.research.google.com/github/tlochan/deep-learning-challenge/blob/main/Alphabet_Soup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
appDf = application_df.copy()
appDf.drop(['EIN','NAME'],axis=1,inplace=True)
appDf.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column
for col in appDf:
  column = appDf[col]
  print(column.name)
  print(len(column.unique()))

APPLICATION_TYPE
17
AFFILIATION
6
CLASSIFICATION
71
USE_CASE
5
ORGANIZATION
4
STATUS
2
INCOME_AMT
9
SPECIAL_CONSIDERATIONS
2
ASK_AMT
8747
IS_SUCCESSFUL
2

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
appDf['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    appDf['APPLICATION_TYPE'] = appDf['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
appDf['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_value_counts = appDf['CLASSIFICATION'].value_counts()
class_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value_counts[class_value_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classes = appDf['CLASSIFICATION'].unique()
print(classes)
vals_to_keep =['C1000','C2000','C1200','C3000','C2100']
classifications_to_replace = [i for i in classes if i not in vals_to_keep]

# Replace in dataframe
for cls in classifications_to_replace:
    appDf['CLASSIFICATION'] = appDf['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
appDf['CLASSIFICATION'].value_counts()

['C1000' 'C2000' 'C3000' 'C1200' 'C2700' 'C7000' 'C7200' 'C1700' 'C4000'
 'C7100' 'C2800' 'C6000' 'C2100' 'C1238' 'C5000' 'C7120' 'C1800' 'C4100'
 'C1400' 'C1270' 'C2300' 'C8200' 'C1500' 'C7210' 'C1300' 'C1230' 'C1280'
 'C1240' 'C2710' 'C2561' 'C1250' 'C8000' 'C1245' 'C1260' 'C1235' 'C1720'
 'C1257' 'C4500' 'C2400' 'C8210' 'C1600' 'C1278' 'C1237' 'C4120' 'C2170'
 'C1728' 'C1732' 'C2380' 'C1283' 'C1570' 'C2500' 'C1267' 'C3700' 'C1580'
 'C2570' 'C1256' 'C1236' 'C1234' 'C1246' 'C2190' 'C4200' 'C0' 'C3200'
 'C5200' 'C1370' 'C2600' 'C1248' 'C6100' 'C1820' 'C1900' 'C2150']

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
print(appDf.dtypes)
print(appDf.columns)

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object
Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
cat_dummies = pd.get_dummies(appDf[['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION','INCOME_AMT', 'SPECIAL_CONSIDERATIONS']])
mergedDf = pd.concat([appDf,cat_dummies],axis=1)
mergedDf.drop(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION','INCOME_AMT', 'SPECIAL_CONSIDERATIONS'],axis=1,inplace=True)
mergedDf.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
X = mergedDf.copy()
X.drop('IS_SUCCESSFUL',axis=1,inplace=True)
y = mergedDf['IS_SUCCESSFUL'].values.reshape(-1,1)

# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 random_state=97)
print(X_train.shape)
print(X_test.shape)

(25724, 43)
(8575, 43)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_features = len(X_train_scaled[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=5,activation='relu', input_dim=num_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=5,activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 220

 dense_1 (Dense)             (None, 5)                 30

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 256 (1.00 KB)
Trainable params: 256 (1.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy',
           optimizer='adam',
           metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 10s 9ms/step - loss: 0.6445 - accuracy: 0.6683
Epoch 2/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5804 - accuracy: 0.7208
Epoch 3/100
804/804 [==============================] - 10s 13ms/step - loss: 0.5670 - accuracy: 0.7277
Epoch 4/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5635 - accuracy: 0.7278
Epoch 5/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5616 - accuracy: 0.7275
Epoch 6/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5596 - accuracy: 0.7288
Epoch 7/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5584 - accuracy: 0.7295
Epoch 8/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5577 - accuracy: 0.7290
Epoch 9/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5569 - accuracy: 0.7298
Epoch 10/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5566 - accuracy: 0.7289
Epoch 11/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5561 - accuracy: 0.7298
Epoch 12/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5558 - accuracy: 0.7297
Epoch 13/100
804/804 [==============================] - 5s 7ms/step - loss: 0.5556 - accuracy: 0.7290
Epoch 14/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5553 - accuracy: 0.7287
Epoch 15/100
804/804 [==============================] - 10s 13ms/step - loss: 0.5547 - accuracy: 0.7291
Epoch 16/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5544 - accuracy: 0.7307
Epoch 17/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5540 - accuracy: 0.7301
Epoch 18/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5538 - accuracy: 0.7297
Epoch 19/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5536 - accuracy: 0.7309
Epoch 20/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5530 - accuracy: 0.7317
Epoch 21/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5530 - accuracy: 0.7310
Epoch 22/100
804/804 [==============================] - 12s 14ms/step - loss: 0.5530 - accuracy: 0.7300
Epoch 23/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5528 - accuracy: 0.7307
Epoch 24/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5524 - accuracy: 0.7308
Epoch 25/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5525 - accuracy: 0.7310
Epoch 26/100
804/804 [==============================] - 12s 14ms/step - loss: 0.5524 - accuracy: 0.7304
Epoch 27/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5522 - accuracy: 0.7307
Epoch 28/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5520 - accuracy: 0.7313
Epoch 29/100
804/804 [==============================] - 10s 13ms/step - loss: 0.5518 - accuracy: 0.7317
Epoch 30/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5516 - accuracy: 0.7310
Epoch 31/100
804/804 [==============================] - 9s 12ms/step - loss: 0.5515 - accuracy: 0.7299
Epoch 32/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5511 - accuracy: 0.7311
Epoch 33/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5516 - accuracy: 0.7308
Epoch 34/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5512 - accuracy: 0.7308
Epoch 35/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5510 - accuracy: 0.7305
Epoch 36/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5510 - accuracy: 0.7311
Epoch 37/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5509 - accuracy: 0.7316
Epoch 38/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5509 - accuracy: 0.7328
Epoch 39/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5510 - accuracy: 0.7302
Epoch 40/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5508 - accuracy: 0.7307
Epoch 41/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5508 - accuracy: 0.7310
Epoch 42/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5508 - accuracy: 0.7320
Epoch 43/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5505 - accuracy: 0.7310
Epoch 44/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5505 - accuracy: 0.7306
Epoch 45/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5506 - accuracy: 0.7312
Epoch 46/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5504 - accuracy: 0.7312
Epoch 47/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5504 - accuracy: 0.7318
Epoch 48/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5502 - accuracy: 0.7312
Epoch 49/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5505 - accuracy: 0.7310
Epoch 50/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5503 - accuracy: 0.7311
Epoch 51/100
804/804 [==============================] - 13s 17ms/step - loss: 0.5502 - accuracy: 0.7318
Epoch 52/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5502 - accuracy: 0.7323
Epoch 53/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5504 - accuracy: 0.7324
Epoch 54/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5503 - accuracy: 0.7305
Epoch 55/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5504 - accuracy: 0.7303
Epoch 56/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5503 - accuracy: 0.7318
Epoch 57/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5501 - accuracy: 0.7320
Epoch 58/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5501 - accuracy: 0.7317
Epoch 59/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5498 - accuracy: 0.7318
Epoch 60/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5500 - accuracy: 0.7317
Epoch 61/100
804/804 [==============================] - 11s 13ms/step - loss: 0.5496 - accuracy: 0.7335
Epoch 62/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5499 - accuracy: 0.7311
Epoch 63/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5498 - accuracy: 0.7311
Epoch 64/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5498 - accuracy: 0.7317
Epoch 65/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5498 - accuracy: 0.7322
Epoch 66/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5497 - accuracy: 0.7323
Epoch 67/100
804/804 [==============================] - 10s 13ms/step - loss: 0.5498 - accuracy: 0.7327
Epoch 68/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5495 - accuracy: 0.7325
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5495 - accuracy: 0.7318
Epoch 70/100
804/804 [==============================] - 11s 13ms/step - loss: 0.5496 - accuracy: 0.7322
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5494 - accuracy: 0.7317
Epoch 72/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5496 - accuracy: 0.7327
Epoch 73/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5495 - accuracy: 0.7316
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5494 - accuracy: 0.7330
Epoch 75/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5493 - accuracy: 0.7320
Epoch 76/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5494 - accuracy: 0.7321
Epoch 77/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5494 - accuracy: 0.7330
Epoch 78/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5493 - accuracy: 0.7313
Epoch 79/100
804/804 [==============================] - 11s 13ms/step - loss: 0.5492 - accuracy: 0.7323
Epoch 80/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5493 - accuracy: 0.7324
Epoch 81/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5495 - accuracy: 0.7324
Epoch 82/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5493 - accuracy: 0.7316
Epoch 83/100
804/804 [==============================] - 12s 14ms/step - loss: 0.5493 - accuracy: 0.7323
Epoch 84/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5492 - accuracy: 0.7322
Epoch 85/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5492 - accuracy: 0.7338
Epoch 86/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5492 - accuracy: 0.7321
Epoch 87/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5492 - accuracy: 0.7326
Epoch 88/100
804/804 [==============================] - 13s 16ms/step - loss: 0.5491 - accuracy: 0.7316
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5491 - accuracy: 0.7331
Epoch 90/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5491 - accuracy: 0.7323
Epoch 91/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5491 - accuracy: 0.7322
Epoch 92/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5490 - accuracy: 0.7317
Epoch 93/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5491 - accuracy: 0.7311
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5490 - accuracy: 0.7324
Epoch 95/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5490 - accuracy: 0.7329
Epoch 96/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5488 - accuracy: 0.7325
Epoch 97/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5490 - accuracy: 0.7320
Epoch 98/100
280/804 [=========>....................] - ETA: 9s - loss: 0.5487 - accuracy: 0.7330

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5610 - accuracy: 0.7247 - 537ms/epoch - 2ms/step
Loss: 0.5609517097473145, Accuracy: 0.7246647477149963

In [ ]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')